
### 400 Bad Request wrong user
GET http://localhost:8080/notifications/users/w?page=1

### 400 Bad Request wrong page
GET http://localhost:8080/notifications/users/4?page=r

### 404 Not Found. Non existing user
GET http://localhost:8080/notifications/users/154545

### 404 Not Found. Non existing page
GET http://localhost:8080/notifications/users/4?page=6544

### Get all notifications by user id 4 (page 0 by default)
GET http://localhost:8080/notifications/users/4

### Get all notifications by user id 4 of page 1
GET http://localhost:8080/notifications/users/4?page=1



### Delete all notifications of existing user
DELETE http://localhost:8080/notifications/users/2

### 404 Not Found. Non existing user
DELETE http://localhost:8080/notifications/users/1111

### 400 Bad Request.  Wrong input
DELETE http://localhost:8080/notifications/users/r34s

### 404 Not Found. Non existing user with negative id
DELETE http://localhost:8080/notifications/users/-1




### Delete notification by notification id
DELETE http://localhost:8080/notifications/48

### 404 Not Found. Non existing notification id
DELETE http://localhost:8080/notifications/1111

### 400 Bad Request. Wrong input parameter of id
DELETE http://localhost:8080/notifications/zzz