version: '3.3'
services:
  notification_database:
    image: postgres
    container_name: notification_database
    environment:
      TZ: Europe/Kyiv
      POSTGRES_DB: notification_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    restart: on-failure
    ports:
      - "5432:5432"